version: "3.7"
services:
  postgres:
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - docker-compose-assignment-1
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  drupal:
    image: drupal
    volumes:
      - drupal-modules:/var/www/html/modules 
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    networks:
      - docker-compose-assignment-1
    ports:
      - "8080:80"

volumes:
  postgres:
      external: true
  drupal-modules:
      external: true
  drupal-profiles:
      external: true
  drupal-sites:
      external: true
  drupal-themes:
      external: true
  
networks:
  docker-compose-assignment-1:
    external: true


#  100  docker container run -d --rm --name postgres -v postgres:/var/lib/postgresql/data --network docker-compose-assignment-1 -e POSTGRES_DB=drupal -e POSTGRES_USER=user -e POSTGRES_PASSWORD=pass postgres:11
#  101  docker container run -d --rm --name drupal --network docker-compose-assignment-1 -p 8080:80 -v drupal-modules:/var/www/html/modules -v drupal-profiles:/var/www/html/profiles -v drupal-sites:/var/www/html/sites -v drupal-themes:/var/www/html/themes drupal

